### ISSUE TITLE
Failed to load IYO see doc from investment agreements page

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/app_backend#133]
Error when loading investment agreement details 5722646637445120
Related to broken JWTs?

```
401 Client Error: None for url: https://staging.itsyou.online/api/users/sabrinasadik/see/Internal%20Token%20Offering%205722646637445120/threefold?version=latest (/base/data/home/apps/e~tff-backend/20170922t124238.404284470723856536/framework/setup_functions.py:176)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/e~tff-backend/20170922t124238.404284470723856536/libs/mcfw/restapi.py", line 188, in get
    self.write_result(self.run(f, args, kwargs))
  File "/base/data/home/apps/e~tff-backend/20170922t124238.404284470723856536/libs/mcfw/restapi.py", line 276, in run
    result = run(f, args, kwargs)
  File "/base/data/home/apps/e~tff-backend/20170922t124238.404284470723856536/libs/mcfw/rpc.py", line 182, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~tff-backend/20170922t124238.404284470723856536/libs/mcfw/restapi.py", line 91, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/e~tff-backend/20170922t124238.404284470723856536/libs/mcfw/rpc.py", line 166, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~tff-backend/20170922t124238.404284470723856536/libs/mcfw/rpc.py", line 144, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~tff-backend/20170922t124238.404284470723856536/plugins/tff_backend/api/investor.py", line 42, in api_get_investment_agreement
    return get_investment_agreement_details(agreement_id)
  File "/base/data/home/apps/e~tff-backend/20170922t124238.404284470723856536/libs/mcfw/rpc.py", line 166, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~tff-backend/20170922t124238.404284470723856536/libs/mcfw/rpc.py", line 144, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~tff-backend/20170922t124238.404284470723856536/plugins/tff_backend/bizz/investor.py", line 439, in get_investment_agreement_details
    see_document = get_see_document(iyo_organization_id, username, agreement.iyo_see_id)
  File "/base/data/home/apps/e~tff-backend/20170922t124238.404284470723856536/libs/mcfw/rpc.py", line 166, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~tff-backend/20170922t124238.404284470723856536/libs/mcfw/rpc.py", line 144, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~tff-backend/20170922t124238.404284470723856536/plugins/tff_backend/bizz/iyo/see.py", line 33, in get_see_document
    result = client.api.users.GetSeeObject(uniqueid, organization_id, username, query_params=query_params)
  File "/base/data/home/apps/e~tff-backend/20170922t124238.404284470723856536/plugins/its_you_online_auth/libs/itsyouonline/users_service.py", line 577, in GetSeeObject
    return self.client.get(uri, None, headers, query_params, content_type)
  File "/base/data/home/apps/e~tff-backend/20170922t124238.404284470723856536/plugins/its_you_online_auth/libs/itsyouonline/client.py", line 68, in get
    return self._handle_data(uri, data, headers, params, content_type, self.session.get)
  File "/base/data/home/apps/e~tff-backend/20170922t124238.404284470723856536/plugins/its_you_online_auth/libs/itsyouonline/client.py", line 55, in _handle_data
    res.raise_for_status()
  File "/base/data/home/apps/e~tff-backend/20170922t124238.404284470723856536/libs/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 401 Client Error: None for url: https://staging.itsyou.online/api/users/sabrinasadik/see/Internal%20Token%20Offering%205722646637445120/threefold?version=latest
```

**Comment by lucasvanhalst** [comment]
Pretty sure this is related to the broken JWT's. I'm just going to remove all sessions that do not have enough scopes
