### ISSUE TITLE
Server error in friend.is_in_roles

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/app_backend#186]
```
04:20:53.670
Incoming Rogerthat callback: (/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/plugins/rogerthat_api/callbacks.py:46)
{u'callback_name': None, u'params': {u'service_identity': u'+default+', u'user_details': [{u'public_key': None, u'name': u'***', u'language': u'nl_NL', u'app_id': u'em-be-threefold-token', u'avatar_url': u'https://rogerth.at/unauthenticated/mobi/cached/avatar/6678601785671680', u'public_keys': [{u'index': u'root', u'name': u'threefold', u'algorithm': u'ed25519', u'public_key': u'***'}], u'email': ***@itsyou.online'}], u'roles': [{u'creation_time': 1505476357, u'type': u'synced', u'id': 5751832013963264L, u'name': u'members'}, {u'creation_time': 1504168038, u'type': u'synced', u'id': 5765785288966144L, u'name': u'invited'}]}, u'method': u'friend.is_in_roles', u'id': u'2016d826-b92b-11e7-8ca3-f14503ca8f6b'}

04:20:53.671
Current user: ***@itsyou.online:em-be-threefold-token (/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/plugins/tff_backend/rogerthat_callbacks.py:74)


04:20:53.685
Incoming friend.is_in_roles Rogerthat callback failed. (/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/framework/setup_functions.py:176)
Traceback (most recent call last):
  File "/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/plugins/rogerthat_api/callbacks.py", line 58, in process_callback
    response['result'] = m(rt_settings, id_, **params)
  File "/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/plugins/tff_backend/rogerthat_callbacks.py", line 173, in friend_is_in_roles
    return is_user_in_roles(user_details[0], roles)
  File "/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/libs/mcfw/rpc.py", line 166, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/libs/mcfw/rpc.py", line 144, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/plugins/tff_backend/bizz/user.py", line 269, in is_user_in_roles
    if has_access_to_organization(client, organization_id, username):
  File "/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/plugins/its_you_online_auth/bizz/authentication.py", line 141, in has_access_to_organization
    r = client.api.organizations.UserIsMember(username, organization_id).json()
  File "/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/plugins/its_you_online_auth/libs/itsyouonline/organizations_service.py", line 417, in UserIsMember
    uri = self.client.base_url + "/organizations/" + globalid + "/users/ismember/" + username
TypeError: coercing to Unicode: need string or buffer, NoneType found

04:20:53.685
Response for incoming friend.is_in_roles Rogerthat callback: (/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/plugins/rogerthat_api/callbacks.py:69)
{'error': 'coercing to Unicode: need string or buffer, NoneType found', 'id': u'2016d826-b92b-11e7-8ca3-f14503ca8f6b', 'result': None}
```

**Comment by lucasvanhalst** [comment]
Should also be fixed now
