### ISSUE TITLE
Error happened when adding user to PUBLIC role

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/app_backend#188]
```
Queue: default (/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/framework/setup_functions.py:195)
deferred.run(plugins.tff_backend.bizz.user.add_user_to_public_role,
             {'public_key': None, 'name': None, 'language': u'en', 'app_id': u'em-be-threefold-token', 'avatar_url': u'https://rogerth.at/unauthenticated/mobi/cached/avatar/5426923249860608', 'public_keys': [], 'email': u'***@itsyou.online'})

This deferred.run already failed 9 times! (/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/framework/setup_functions.py:162)

403 Client Error: None for url: https://itsyou.online/api/organizations/threefold.members/users/ismember/andreas_achillea_3 (/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/framework/setup_functions.py:174)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/framework/setup_functions.py", line 200, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/libs/mcfw/rpc.py", line 166, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/libs/mcfw/rpc.py", line 144, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/plugins/tff_backend/bizz/user.py", line 280, in add_user_to_public_role
    if has_access_to_organization(client, organization_id, username):
  File "/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/plugins/its_you_online_auth/bizz/authentication.py", line 141, in has_access_to_organization
    r = client.api.organizations.UserIsMember(username, organization_id).json()
  File "/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/plugins/its_you_online_auth/libs/itsyouonline/organizations_service.py", line 418, in UserIsMember
    return self.client.get(uri, None, headers, query_params, content_type)
  File "/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/plugins/its_you_online_auth/libs/itsyouonline/client.py", line 68, in get
    return self._handle_data(uri, data, headers, params, content_type, self.session.get)
  File "/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/plugins/its_you_online_auth/libs/itsyouonline/client.py", line 55, in _handle_data
    res.raise_for_status()
  File "/base/data/home/apps/e~tff-backend/20171024t172200.405031133535934583/libs/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: None for url: https://itsyou.online/api/organizations/threefold.members/users/ismember/***
```

**Comment by lucasvanhalst** [comment]
Should be fixed by https://github.com/rogerthat-platform/plugin-its-you-online-auth/commit/d17c47632f5714a8a8104546c613341237d7d796
