### ISSUE TITLE
Server error in new conversation webhook

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/app_backend#199]
```
12:34:48.647
Incomming call from intercom: { (/base/data/home/apps/e~tff-backend/20171027t111511.405094806781228143/plugins/intercom_support/intercom_webhooks.py:47)
  "type" : "notification_event",
  "app_id" : "***",
  "data" : {
    "type" : "notification_event_data",
    "item" : {
      "type" : "conversation",
      "id" : "***",
      "created_at" : 1509269627,
      "updated_at" : 1509269627,
      "user" : {
        "type" : "user",
        "id" : "***",
        "user_id" : null,
        "name" : "***",
        "email" : "***@hotmail.com"
      },
      "assignee" : {
        "type" : "nobody_admin",
        "id" : null
      },
      "conversation_message" : {
        "type" : "conversation_message",
        "id" : "144716249",
        "subject" : "<p>meeting 26/10/2017</p>",
        "body" : "***</p>",
        "author" : {
          "type" : "user",
          "id" : "***"
        },
        "attachments" : [ ]
      },
      "conversation_parts" : {
        "type" : "conversation_part.list",
        "conversation_parts" : [ ],
        "total_count" : 0
      },
      "open" : true,
      "read" : true,
      "metadata" : { },
      "tags" : {
        "type" : "tag.list",
        "tags" : [ ]
      },
      "links" : {
        "conversation_web" : "***"
      }
    }
  },
  "links" : { },
  "id" : "notif_***",
  "topic" : "conversation.user.created",
  "delivery_status" : "retry",
  "delivery_attempts" : 2,
  "delivered_at" : 0,
  "first_sent_at" : 1509269688,
  "created_at" : 1509269628,
  "self" : null
}


12:34:48.647
Parent cannot have incomplete key (/base/data/home/apps/e~tff-backend/20171027t111511.405094806781228143/framework/setup_functions.py:176)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/e~tff-backend/20171027t111511.405094806781228143/plugins/intercom_support/intercom_webhooks.py", line 53, in post
    handler(payload)
  File "/base/data/home/apps/e~tff-backend/20171027t111511.405094806781228143/plugins/intercom_support/bizz/webhooks.py", line 87, in conversation_user_created
    ic = models.IntercomConversation.create_key(intercom_user_id, intercom_support_message_id).get()
  File "/base/data/home/apps/e~tff-backend/20171027t111511.405094806781228143/plugins/intercom_support/models.py", line 50, in create_key
    return ndb.Key(cls, chat_id, parent=User.create_key(user_id), namespace=NAMESPACE)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/key.py", line 235, in __new__
    self.__namespace) = self._parse_from_args(**kwargs)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/key.py", line 281, in _parse_from_args
    'Parent cannot have incomplete key')
BadArgumentError: Parent cannot have incomplete key
```

**Comment by lucasvanhalst** [comment]
Should've been fixed by https://github.com/rogerthat-platform/plugin-intercom-support/commit/82f2c617aa65e9678644878d13c7456fa9dfe3ce
